### ISSUE TITLE
Should the spelling of Wednesdays be reviewed ?

### ISSUE THREAD

**Issue by jeis2497052** [awslabs/deeplearning-cfn#10]
Hi All,

in the example below I see:

examples/tensorflow/models/textsum/data/vocab:8711:0: "wednesdy" is a misspelling of "wednesdays"

**Comment by lupesko** [comment]
It seems to indeed be an incorrect spelling, but it is part of the vocab file which is typically automatically generated by counting words in a corpus, so I wonder.
At any case, this is a submodule pointing to (TensorFlow Models)[https://github.com/tensorflow/models] - I suggest you file a PR for that repo.

Closing this issue.
If closed in error feel free to re-open and comment.
