### ISSUE TITLE
IS it possible to set instance storage with this template?

### ISSUE THREAD

**Issue by melontron** [awslabs/deeplearning-cfn#16]
The default storage is limited to 50GB, what can I do in case I want more than 50GB?

**Comment by nswamy** [comment]
You can choose to use a different AMI and modify the template to use that AMI Id or extend the template to create a new EBS volume and attach to each instance,  I encourage you to make a contribution to this repo if you go this route. I can help you with review etc.,

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html
